### ISSUE TITLE
Refactor how the application uses node API

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-dictaphone#14]
#1 The database must be given the same name as the app i.e. com.enonic.app.dictaphone (in order to avoid collisions)
#2 The data must not be stored as a JSON blob, but shredded into separate properties i.e. title, description - so we can search for memos on on the server

Also, a question - what are the "volumedata" etc things stored in the JSON??

**Comment by sigdestad** [comment]
NB! With these changes we must release a version 2.0

**Comment by vbradnitski** [comment]
'volumeData' stores array of Y-coordnates for media waveform
![image](https://user-images.githubusercontent.com/8234920/38306876-96aaddb8-381a-11e8-9f90-6cc710530e24.png)

**Comment by vbradnitski** [comment]
'volumeData' stores array of Y-coordinates for media waveform
![image](https://user-images.githubusercontent.com/8234920/38307045-1840665e-381b-11e8-834c-7e8ed7d6f733.png)

**Comment by sigdestad** [comment]
Ok, so fine voluemdata should be a separate property then (maybe a binary?). Basically, every data field must be stored as a separate property of matching type, and indexed only if needed.
